language: erlang

matrix:
  include:
    - os: linux
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7.11
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7.11
        - VENV=venv
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.4.4
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.4.4
        - VENV=venv
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.5.1
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=3.5.1
        - VENV=venv

script:
  - source tests/test_multibuild.sh
