# Set TEST_BUILDS=1 to run library_builders tests

language: generic

matrix:
  include:
    - os: linux
      dist: precise
      env:
        - TEST_BUILDS=1
    - os: linux
      dist: trusty
      env:
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=2.6
        - TEST_BUILDS=1
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=2.6
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=2.7.11
        - TEST_BUILDS=1
    - os: osx
      language: objective-c
      env:
        - PYTHON_VERSION=2.7.11
        - VENV=venv
    - os: osx
      osx_image: xcode6.4
      env:
        - PYTHON_VERSION=3.3
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
    - os: osx
      env:
        - PYTHON_VERSION=3.4.4
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.5.1
    - os: osx
      env:
        - PYTHON_VERSION=3.5.1
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=3.6.0
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-2.6
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-4.0
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.0
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.1
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.3
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.4
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.6
        - VENV=venv
    - os: osx
      env:
        - PYTHON_VERSION=pypy-5.7
        - VENV=venv

script:
  - source tests/test_multibuild.sh
